name: clrs

channels:
  - defaults
  - conda-forge

dependencies:
  - python
  - pip
  - git
  - jupyterlab # for IDE

  - pandas
  - scikit-learn<1.3
  - scikit-plot
  - lightgbm
  - xgboost
  - optuna
  - sparse
  - chainladder
  - matplotlib
